[package]
name = "kailua-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
c-kzg.workspace = true
clap.workspace = true
hex.workspace = true
human_bytes.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true

alloy = { workspace = true, features = ["full", "kzg"] }
alloy-primitives = { workspace = true, features = ["map-hashbrown"] }

kailua-build.workspace = true
kailua-common = { workspace = true, features = ["offline"] }
kailua-contracts.workspace = true

kona-cli.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-std-fpvm.workspace = true

bonsai-sdk.workspace = true
boundless-market.workspace = true
risc0-ethereum-contracts.workspace = true
risc0-zkvm.workspace = true

#SOON
soon-derive.workspace = true
soon-primitives.workspace = true

[features]
default = ["test-tools"]
prove = ["risc0-zkvm/prove"]
cuda = ["risc0-zkvm/cuda"]
metal = ["risc0-zkvm/metal"]
disable-dev-mode = ["risc0-zkvm/disable-dev-mode"]
rebuild-fpvm = ["kailua-build/rebuild-fpvm"]
# Feature for offline generator tool
test-tools = ["kailua-common/__test"]

[[bin]]
name = "kailua-offline"
path = "src/bins/offline.rs"

[[bin]]
name = "soon-offline-generator"
path = "src/bins/offgen.rs"
